[package]
name = "arciumintnftgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", default-features = false, features = ["token"] }
mpl-token-metadata = "1.11.0"
spl-memo = { version = "1.0.0", features = ["v1"] }

[patch.crates-io]
solana-program = "=2.1.0"
spl-token = "=4.0.0"
spl-memo = "=1.0.0"

[features]
default = []
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build"
]

[lib]
crate-type = ["cdylib"]
