[package]
name = "arciumintnftgen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["token"] }
mpl-token-metadata = "4.1.2"
spl-memo = "4.0.0"

[features]
default = []
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build"
]
