[package]
name = "arciumintnftgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl  = { version = "0.31.1", default-features = false, features = ["token"] }

mpl-token-metadata = { version = "4.1.2", default-features = false }

solana-program = { version = "1.18.17", default-features = false }

[features]
default = []
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build"
]

[lib]
crate-type = ["cdylib"]

[patch.crates-io]
solana-program = "=1.18.17"
