[package]
name = "arciumintnftgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.32.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.0", features = ["idl-build"] }

[features]
default = ["idl-build"]
idl-build = [
  "anchor-lang/idl-build",
  "anchor-spl/idl-build"
]
