[programs.devnet]
usernftcreator = { path = "programs/usernftcreator", address = "BajbA5RqB7CnhsbNKtpS6oQr8wNwXYBZxg4AK4jRrD9i" }

[provider]
cluster = "devnet"
wallet = "wallet.json"

[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[scripts]
test = "mocha -t 1000000 tests/"
