[programs.devnet]
arciumintnftgen = "FJbJDhJ8cRN2qjMwqQw5UwbqznjXxDxPwQtpzaojLaHi"

[provider]
cluster = "devnet"
wallet = "wallet.json"

[scripts]
test = "mocha -t 1000000 tests/"

[toolchain]
anchor_version = "0.31.1"
