[programs.devnet]
arciumintnftgen = "Hx6jdiv9A7LVoa83LYRNXb2SaTGTPdfKQ75hB3hyRuHW"

[provider]
cluster = "devnet"
wallet = "wallet.json"

[scripts]
test = "mocha -t 1000000 tests/"

[toolchain]
anchor_version = "0.31.1"
