[programs.devnet]
arciumintnftgen = "22aiFCK8g424HHtkhcZfJTrCx34eQMcRHNgsWGyXB8Vn"

[provider]
cluster = "devnet"
wallet = "wallet.json"

[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[scripts]
test = "mocha -t 1000000 tests/"
