[toolchain]
anchor_version = "0.32.1"
solana_version = "3.1.15"
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.devnet]
disc_mpc = "DhTtJLxGddjgxi8qGbX2scdTHoaf2XCa89GNjfSWtazJ"

[programs.localnet]
disc_mpc = "DhTtJLxGddjgxi8qGbX2scdTHoaf2XCa89GNjfSWtazJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
