[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
disc_mpc = "HLjbzyyL81hRk8CM4TyyP4GSS7N89KW3Tv4NUsHBc5ij"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]

[workspace]
members = [
    "programs",
    "encrypted-ixs"
]
