[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.devnet]
disc_mpc = "BeTs4bmTq2XqodfRXEniy3fqRMD5hpDbwr3m4dZcBayi"

[programs.localnet]
disc_mpc = "BeTs4bmTq2XqodfRXEniy3fqRMD5hpDbwr3m4dZcBayi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
