name: Arcium MPC CI

on:
  workflow_dispatch:
  push:
    paths:
      - "arcium/**"

jobs:
  arcium-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev jq

      
      - name: Install Rust nightly (NEW ENOUGH)
        run: |
          rustup toolchain install nightly-2024-02-15 --profile minimal
          rustup default nightly-2024-02-15
          rustc --version
          cargo --version

      - name: Install Solana CLI
        run: |
          curl -fL https://github.com/solana-labs/solana/releases/download/v1.18.26/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
          tar -xjf solana.tar.bz2
          sudo mv solana-release/bin/* /usr/local/bin/
          solana --version

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Yarn
        run: |
          corepack enable
          yarn --version

      - name: Install Anchor 0.32.1
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.32.1
          avm use 0.32.1
          anchor --version

      - name: Install Arcium CLI
        run: |
          curl -fL https://bin.arcium.com/download/arcium_x86_64_linux_0.6.0-alpha -o /tmp/arcium
          chmod +x /tmp/arcium
          sudo mv /tmp/arcium /usr/local/bin/arcium
          arcium --version

      
      - name: Build Arcium MPC
        env:
          RUSTUP_TOOLCHAIN: nightly-2024-02-15
          CARGO: cargo +nightly-2024-02-15
        run: |
          cd arcium/disc_mpc
          yarn install
          arcium build --skip-keys-sync
