name: Arcium Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Solana 2.3.0 (mirror)
        run: |
          wget https://solana-mirror.s3.amazonaws.com/v2.3.0/solana-install-init-x86_64-unknown-linux-gnu
          chmod +x solana-install-init-x86_64-unknown-linux-gnu
          ./solana-install-init-x86_64-unknown-linux-gnu --no-modify-path
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          solana --version

      - name: Install Anchor 0.32.1
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --force
          avm install 0.32.1
          avm use 0.32.1
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          anchor --version

      - name: Install Arcium toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://install.arcium.com/ | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          arcium --version

      - name: Build Arcium
        run: |
          cd arcium/disc_mpc
          solana --version
          anchor --version
          arcium --version
          arcium build --skip-keys-sync

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arcium-build
          path: arcium/disc_mpc/build
