name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: 1.89.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Rust
      run: |
        rustup self update
        rustup install ${{ env.RUSTUP_TOOLCHAIN }}
        rustup default ${{ env.RUSTUP_TOOLCHAIN }}
        rustc --version
        cargo --version

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version

    - name: Install Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
        avm install 0.31.1
        avm use 0.31.1
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
        export PATH="$HOME/.avm/bin:$PATH"
        anchor --version

    - name: Restore wallet keypair (signer)
      run: |
        echo '${{ secrets.WALLET_KEY }}' > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com
        solana address -k wallet.json

    - name: Restore program keypair
      run: |
        mkdir -p target/deploy
        echo '${{ secrets.PROGRAM_KEYPAIR }}' > target/deploy/arciumintnftgen-keypair.json
        solana address -k target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL to wallet
      run: solana airdrop 2 -k wallet.json || echo "Airdrop failed, continuing anyway"

    - name: Confirm Program ID consistency
      run: |
        echo "Program ID in lib.rs:"
        grep "declare_id!" programs/arciumint-nft-gen/src/lib.rs
        echo "Program ID in Anchor.toml:"
        grep "arciumintnftgen" Anchor.toml
        echo "Program ID from keypair file:"
        solana address -k target/deploy/arciumintnftgen-keypair.json

    - name: Build Anchor program
      run: |
        echo "🔧 Running anchor build..."
        anchor build --skip-lint
        echo "📦 Build complete. Listing .so files:"
        find programs/arciumint-nft-gen/target/deploy -name "*.so" || echo "⚠️ No .so files found."

    - name: Check .so file exists
      run: |
        SO_PATH=$(find programs/arciumint-nft-gen/target/deploy -name "arciumintnftgen.so")
        if [ -z "$SO_PATH" ]; then
          echo "❌ ERROR: .so file not found. Build may have failed."
          exit 1
        fi
        echo "✅ .so file found at $SO_PATH"

    - name: Move .so file to root deploy folder
      run: |
        mkdir -p target/deploy
        cp programs/arciumint-nft-gen/target/deploy/arciumintnftgen.so target/deploy/arciumintnftgen.so

    - name: Deploy Anchor program to devnet
      run: anchor deploy --provider.cluster devnet --provider.wallet wallet.json
