name: Deploy Anchor Program

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install Solana CLI (from GitHub release)
      run: |
        curl -sL https://github.com/solana-labs/solana/releases/download/v1.18.2/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
        tar -xjf solana.tar.bz2
        echo "$PWD/solana-release/bin" >> $GITHUB_PATH
        export PATH="$PWD/solana-release/bin:$PATH"
        solana --version

    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        anchor --version

    - name: Set up wallet
      run: |
        echo "${{ secrets.WALLET_KEY }}" > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Airdrop SOL to wallet
      run: solana airdrop 0.2 || echo "Airdrop failed, continuing anyway"

    - name: Update and clean dependencies
      run: |
        cargo update -p anchor-spl
        cargo update -p anchor-lang
        cargo update -p solana-program
        cargo clean
      working-directory: programs/arciumint-nft-gen

    - name: Build program with Cargo
      run: cargo build --manifest-path Cargo.toml -Znext-lockfile-bump
      working-directory: programs/arciumint-nft-gen

    - name: Deploy program
      run: anchor deploy
      working-directory: programs/arciumint-nft-gen
