name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: 1.89.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Rust
      run: |
        rustup self update
        rustup install ${{ env.RUSTUP_TOOLCHAIN }}
        rustup default ${{ env.RUSTUP_TOOLCHAIN }}
        rustc --version
        cargo --version

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version

    - name: Install Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
        avm install 0.31.1
        avm use 0.31.1
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
        export PATH="$HOME/.avm/bin:$PATH"
        anchor --version

    - name: Restore wallet keypair (signer)
      run: |
        echo '${{ secrets.WALLET_KEY }}' > programs/arciumint-nft-gen/wallet.json
        solana config set --keypair programs/arciumint-nft-gen/wallet.json
        solana config set --url https://api.devnet.solana.com
        solana address -k programs/arciumint-nft-gen/wallet.json

    - name: Restore program keypair (must match declare_id!)
      run: |
        mkdir -p target/deploy
        echo '${{ secrets.PROGRAM_KEYPAIR }}' > target/deploy/arciumintnftgen-keypair.json
        echo "Program ID from keypair file:"
        solana address -k target/deploy/arciumintnftgen-keypair.json

    - name: Confirm Program ID consistency
      run: |
        echo "Program ID in lib.rs:"
        grep "declare_id!" programs/arciumint-nft-gen/src/lib.rs
        echo "Program ID in Anchor.toml:"
        grep "arciumintnftgen" Anchor.toml
        echo "Program ID from keypair file:"
        solana address -k target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL to wallet
      run: solana airdrop 0.2 -k programs/arciumint-nft-gen/wallet.json || echo "Airdrop failed, continuing anyway"

    - name: Clean build artifacts
      run: |
        rm -rf target
        rm -rf programs/arciumint-nft-gen/.anchor

    - name: Build Anchor program (after keypair is restored)
      run: |
        ANCHOR_LOG=true anchor build --skip-lint

    - name: Deploy Anchor program to devnet
      run: |
        anchor deploy --provider.cluster devnet
