name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: nightly-2024-08-18

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Install Rust nightly
      run: |
        rustup self update
        rustup install ${{ env.RUSTUP_TOOLCHAIN }}
        rustup default ${{ env.RUSTUP_TOOLCHAIN }}
        rustc --version
        cargo --version

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version

    - name: Install Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --force
        avm install 0.31.1
        avm use 0.31.1
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
        export PATH="$HOME/.avm/bin:$PATH"
        anchor --version

    - name: Restore wallet keypair
      run: |
        echo "${{ secrets.WALLET_KEY }}" > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Restore program keypair
      run: |
        mkdir -p programs/arciumint-nft-gen/target/deploy
        echo "${{ secrets.PROGRAM_KEYPAIR }}" > programs/arciumint-nft-gen/target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL to wallet
      run: solana airdrop 0.2 || echo "Airdrop failed, continuing anyway"

    - name: Build and Deploy Anchor Program
      working-directory: programs/arciumint-nft-gen
      run: |
        anchor build --skip-lint -- --locked
        anchor deploy --provider.cluster devnet --provider.wallet ../../wallet.json
