name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: 1.89.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Install Rust
      run: |
        rustup self update
        rustup install ${{ env.RUSTUP_TOOLCHAIN }}
        rustup default ${{ env.RUSTUP_TOOLCHAIN }}
        rustc --version
        cargo --version

    - name: Install Solana CLI via Anza
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana --version

    - name: Install Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force || true
        avm install 0.31.1 || true
        avm use 0.31.1 || true
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
        export PATH="$HOME/.avm/bin:$PATH"
        anchor --version

    - name: Restore wallet keypair
      run: |
        echo '${{ secrets.WALLET_KEY }}' > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Restore program keypair
      run: |
        mkdir -p target/deploy
        echo '${{ secrets.PROGRAM_KEYPAIR }}' > target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL
      run: solana airdrop 1 -k wallet.json || echo "Airdrop failed"

    - name: Confirm Program ID consistency
      run: |
        grep "declare_id!" programs/arciumint-nft-gen/src/lib.rs || true
        grep "arciumintnftgen" Anchor.toml || true
        solana address -k target/deploy/arciumintnftgen-keypair.json || true

    - name: Clean Anchor build
      run: |
        cd programs/arciumint-nft-gen
        anchor clean

    - name: Build Anchor program
      run: |
        cd programs/arciumint-nft-gen
        ANCHOR_LOG=true anchor build --skip-lint
        find target/deploy -name "*.so" || echo "⚠️ No .so files found."
        cd -

    - name: Check .so file exists
      run: |
        SO_PATH=$(find programs/arciumint-nft-gen/target/deploy -name "arciumintnftgen.so")
        if [ -z "$SO_PATH" ]; then
          echo "❌ .so file not found!"
          exit 1
        fi

    - name: Move .so file to root deploy folder
      run: |
        mkdir -p target/deploy
        cp programs/arciumint-nft-gen/target/deploy/arciumintnftgen.so target/deploy/arciumintnftgen.so

    - name: Deploy Anchor program
      run: |
        cd programs/arciumint-nft-gen
        anchor deploy --provider.cluster devnet --provider.wallet ../../wallet.json
