name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: 1.89.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config build-essential libssl-dev

    - name: Install Rust toolchain and add cargo to PATH
      run: |
        rustup self update
        rustup install ${{ env.RUSTUP_TOOLCHAIN }}
        rustup default ${{ env.RUSTUP_TOOLCHAIN }}
        rustc --version
        cargo --version
        # persist cargo bin to PATH for future steps
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Solana CLI via Anza
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        solana --version

    - name: Install Anchor CLI (avm) and add to PATH
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force || true
        avm install 0.31.1 || true
        avm use 0.31.1 || true
        echo "$HOME/.avm/bin" >> $GITHUB_PATH
        anchor --version

    - name: (optional) Install Arcium CLI
      run: |
        curl --proto '=https' --tlsv1.2 -sSfL https://arcium-install.arcium.workers.dev/ | bash || true
        # arcup may add its own bins; add if required
        echo "$HOME/.local/bin" >> $GITHUB_PATH || true

    - name: Restore wallet keypair
      run: |
        echo '${{ secrets.WALLET_KEY }}' > wallet.json
        chmod 600 wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Restore program keypair
      run: |
        mkdir -p target/deploy
        echo '${{ secrets.PROGRAM_KEYPAIR }}' > target/deploy/arciumintnftgen-keypair.json
        chmod 600 target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL (devnet)
      run: |
        solana airdrop 2 -k wallet.json || echo "Airdrop failed (maybe rate-limited)"

    - name: Confirm program id / anchor mapping (debug)
      run: |
        grep "declare_id!" programs/arciumint-nft-gen/src/lib.rs || true
        grep "arciumintnftgen" Anchor.toml || true
        solana address -k target/deploy/arciumintnftgen-keypair.json || true

    - name: Clean Anchor build
      run: anchor clean || true

    - name: Build Anchor program (generate IDL)
      run: |
        # IMPORTANT: do NOT enable 'exclude-accounts' when you want accounts in IDL
        ANCHOR_LOG=true anchor build --skip-lint -- --features idl-build

    - name: Check IDL file exists
      run: |
        if [ ! -f target/idl/arciumintnftgen.json ]; then
          echo "❌ IDL file not found!"
          ls -la target/idl || true
          exit 1
        fi

    - name: Copy IDL to client
      run: |
        mkdir -p client/idl
        cp target/idl/arciumintnftgen.json client/idl/arciumintnftgen.json
        echo "Copied IDL (size): $(wc -c < client/idl/arciumintnftgen.json) bytes"

    - name: Commit and push IDL to repo (if changed)
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github-actions"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add -f client/idl/arciumintnftgen.json
        if git diff --cached --quiet; then
          echo "✅ No changes to commit"
        else
          git commit -m "Add IDL file for frontend build"
          git push origin main
        fi

    - name: Check .so file exists
      run: |
        if [ ! -f target/deploy/arciumintnftgen.so ]; then
          echo "❌ .so file not found!"
          ls -la target/deploy || true
          exit 1
        fi

    - name: Refresh blockhash / show cluster info
      run: |
        solana config set --url https://api.devnet.solana.com
        solana block-height
        solana balance
        sleep 2

    - name: Deploy Anchor program (with retries to avoid transient blockhash issues)
      run: |
        set -e
        attempts=0
        max_attempts=5
        until [ $attempts -ge $max_attempts ]
        do
          echo "Deploy attempt: $((attempts+1))"
          if anchor deploy --provider.cluster devnet --provider.wallet wallet.json; then
            echo "✅ anchor deploy succeeded"
            break
          else
            echo "❌ anchor deploy failed (attempt $((attempts+1)))"
            attempts=$((attempts+1))
            # try to refresh funding or blockhash
            solana airdrop 1 -k wallet.json || true
            sleep 5
          fi
        done
        if [ $attempts -ge $max_attempts ]; then
          echo "🚨 anchor deploy failed after $max_attempts attempts"
          exit 1
        fi
