name: Deploy Anchor Program

on:
  push:
    branches: [main]

env:
  RUSTUP_TOOLCHAIN: nightly-2025-08-01

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2025-08-01
        override: true
        components: rust-src

    - name: Verify Rust toolchain
      run: |
        rustup show
        rustc --version
        cargo --version

    - name: Install Solana CLI v1.18.2
      run: |
        curl -sL https://github.com/solana-labs/solana/releases/download/v1.18.2/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
        tar -xjf solana.tar.bz2
        echo "$PWD/solana-release/bin" >> $GITHUB_PATH
        export PATH="$PWD/solana-release/bin:$PATH"
        solana --version

    - name: Install Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        anchor --version

    - name: Restore wallet keypair
      run: |
        echo "${{ secrets.WALLET_KEY }}" > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Restore program keypair
      run: |
        mkdir -p programs/arciumint-nft-gen/target/deploy
        echo "${{ secrets.PROGRAM_KEYPAIR }}" > programs/arciumint-nft-gen/target/deploy/arciumintnftgen-keypair.json

    - name: Airdrop SOL to wallet
      run: solana airdrop 0.2 || echo "Airdrop failed, continuing anyway"

    - name: Sync Program ID automatically
      working-directory: programs/arciumint-nft-gen
      run: anchor keys list

    - name: Regenerate Cargo.lock with nightly
      working-directory: programs/arciumint-nft-gen
      run: cargo generate-lockfile -Znext-lockfile-bump

    - name: Build Anchor program (nightly)
      working-directory: programs/arciumint-nft-gen
      run: |
        cargo build-bpf
        cargo install --force --path .
        anchor build --skip-lint

    - name: Deploy program to devnet
      working-directory: programs/arciumint-nft-gen
      run: anchor deploy --provider.cluster devnet --provider.wallet ../../wallet.json
