name: Deploy Anchor Program

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust (nightly)
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        source $HOME/.cargo/env
        rustup default nightly
        rustup update

    - name: Install Solana CLI (from GitHub release)
      run: |
        curl -sL https://github.com/solana-labs/solana/releases/download/v1.18.2/solana-release-x86_64-unknown-linux-gnu.tar.bz2 -o solana.tar.bz2
        tar -xjf solana.tar.bz2
        echo "$PWD/solana-release/bin" >> $GITHUB_PATH
        export PATH="$PWD/solana-release/bin:$PATH"
        solana --version

    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        anchor --version

    - name: Set up wallet
      run: |
        echo "${{ secrets.WALLET_KEY }}" > wallet.json
        solana config set --keypair wallet.json
        solana config set --url https://api.devnet.solana.com

    - name: Airdrop SOL to wallet
      run: solana airdrop 2

    - name: Deploy program
      run: |
        anchor build
        anchor deploy
